import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CamisaVetor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Fundo do site alterado para branco */}
      <body className={`${inter.className} bg-white`}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
